Reference: [link](https://rare-technologies.com/word2vec-tutorial/)

In [ ]:
import gensim

In [3]:
sentences = [['first', 'sentence'], ['second', 'sentence']]
# train word2vec on the two sentences
model = gensim.models.Word2Vec(sentences, min_count=1)

In [4]:
model['second']

array([ 0.00106842, -0.00312128,  0.0047069 , -0.00414356, -0.00423598,
       -0.00040327, -0.00029676, -0.00417477, -0.00044186, -0.00328746,
       -0.00270419,  0.00424604,  0.00210823, -0.00187221, -0.00349442,
       -0.00426781, -0.00208468,  0.00252425, -0.00390444,  0.00116104,
        0.00020523,  0.00459912,  0.00336795,  0.00190524, -0.00138593,
        0.00169119,  0.00389097,  0.00472171,  0.00072917, -0.00289813,
       -0.00378115, -0.00122332, -0.0010024 , -0.00361622,  0.0040295 ,
       -0.00152582, -0.00402649,  0.00404417, -0.00057686,  0.0048143 ,
       -0.00257664,  0.0032158 , -0.00269044,  0.00048096,  0.00219135,
        0.00350089, -0.00357451,  0.00349201, -0.00025142,  0.00072228,
        0.00045538, -0.00445417,  0.00306503, -0.00147165,  0.00480565,
        0.00091066,  0.00044831, -0.00163721,  0.00049226,  0.00117763,
        0.00073401,  0.00241021,  0.00398384, -0.00464297,  0.00311831,
       -0.0037067 ,  0.00032445, -0.00475344, -0.00101856, -0.00

In [6]:
model.save('mymodel')
new_model = gensim.models.Word2Vec.load('mymodel')

In [11]:
from gensim.models.keyedvectors import KeyedVectors
gensim.scripts.glove2word2vec.glove2word2vec('glove.6B.50d.txt', 'word2vec_glove.txt')

(400000, 50)

In [12]:
glove_model = KeyedVectors.load_word2vec_format('word2vec_glove.txt', binary=False)

In [13]:
glove_model.wv.most_similar(positive=['woman', 'king'], negative=['man']) # king - man + woman

[('queen', 0.8523603677749634),
 ('throne', 0.7664334177970886),
 ('prince', 0.759214460849762),
 ('daughter', 0.7473883032798767),
 ('elizabeth', 0.7460220456123352),
 ('princess', 0.7424569725990295),
 ('kingdom', 0.7337411642074585),
 ('monarch', 0.7214490175247192),
 ('eldest', 0.7184861898422241),
 ('widow', 0.7099430561065674)]

In [15]:
glove_model.wv.doesnt_match("breakfast cereal dinner lunch".split())

'cereal'

In [17]:
glove_model.wv.similarity('woman', 'man')

0.88603376834235426

In [18]:
glove_model.wv.similarity('woman', 'girl')

0.90652807013092229

In [21]:
# lets try loading glove file itself
del glove_model

In [22]:
import numpy as np
def loadGloveModel(gloveFile):
    print ("Loading Glove Model")
    f = open(gloveFile,'r')
    model = {}
    for line in f:
        splitLine = line.split()
        word = splitLine[0]
        embedding = np.array([float(val) for val in splitLine[1:]])
        model[word] = embedding
    print ("Done.",len(model)," words loaded!")
    return model

In [23]:
manual_load_model = loadGloveModel('glove.6B.50d.txt')

Loading Glove Model
Done. 400000  words loaded!


In [26]:
manual_load_model['man']

array([-0.094386,  0.43007 , -0.17224 , -0.45529 ,  1.6447  ,  0.40335 ,
       -0.37263 ,  0.25071 , -0.10588 ,  0.10778 , -0.10848 ,  0.15181 ,
       -0.65396 ,  0.55054 ,  0.59591 , -0.46278 ,  0.11847 ,  0.64448 ,
       -0.70948 ,  0.23947 , -0.82905 ,  1.272   ,  0.033021,  0.2935  ,
        0.3911  , -2.8094  , -0.70745 ,  0.4106  ,  0.3894  , -0.2913  ,
        2.6124  , -0.34576 , -0.16832 ,  0.25154 ,  0.31216 ,  0.31639 ,
        0.12539 , -0.012646,  0.22297 , -0.56585 , -0.086264,  0.62549 ,
       -0.0576  ,  0.29375 ,  0.66005 , -0.53115 , -0.48233 , -0.97925 ,
        0.53135 , -0.11725 ])

In [27]:
manual_load_model['woman']

array([ -1.81530000e-01,   6.48270000e-01,  -5.82100000e-01,
        -4.94510000e-01,   1.54150000e+00,   1.34500000e+00,
        -4.33050000e-01,   5.80590000e-01,   3.55560000e-01,
        -2.51840000e-01,   2.02540000e-01,  -7.16430000e-01,
         3.06100000e-01,   5.61270000e-01,   8.39280000e-01,
        -3.80850000e-01,  -9.08750000e-01,   4.33260000e-01,
        -1.44360000e-02,   2.37250000e-01,  -5.37990000e-01,
         1.77730000e+00,  -6.64330000e-02,   6.97950000e-01,
         6.92910000e-01,  -2.67390000e+00,  -7.68050000e-01,
         3.39290000e-01,   1.96950000e-01,  -3.52450000e-01,
         2.29200000e+00,  -2.74110000e-01,  -3.01690000e-01,
         8.52860000e-04,   1.69230000e-01,   9.14330000e-02,
        -2.36100000e-02,   3.62360000e-02,   3.44880000e-01,
        -8.39470000e-01,  -2.51740000e-01,   4.21230000e-01,
         4.86160000e-01,   2.23250000e-02,   5.57600000e-01,
        -8.52230000e-01,  -2.30730000e-01,  -1.31380000e+00,
         4.87640000e-01,

In [28]:
import math

def dot_product(v1, v2):
    return sum(map(lambda x: x[0] * x[1], zip(v1, v2)))

def cosine_measure(v1, v2):
    prod = dot_product(v1, v2)
    len1 = math.sqrt(dot_product(v1, v1))
    len2 = math.sqrt(dot_product(v2, v2))
    return prod / (len1 * len2)


In [29]:
cosine_measure(manual_load_model['man'], manual_load_model['woman'])

0.8860337718495821